backend:
  name: github
  repo: dissko/ttpl
  branch: main


media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: dk3keqspt
    api_key: 132597831268894

collections:
  # HOME
  - name: "homepage"
    label: "Homepage - Items"
    description: "These are the items that appear on the bottom of the homepage."
    folder: "content/homepage-items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Order On Homepage", name: "order", widget: "number", required: true, hint: "This will determine the order in which items appear on the homepage." }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown", required: true, hint: "Supports rich text formatting, including bolding, new lines, and hyperlinks." }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false, hint: "Optional. If not set and a link is set, the button text will default to 'Learn More'" }
      - { label: "Button URL", name: "buttonUrl", widget: "string", required: false }
      - label: "Image Orientation"
        name: "imageOrientation"
        widget: "select"
        hint: "This will determine the layout of the image relative to the text."
        options:
          - { label: "Top", value: "top" }
          - { label: "Left", value: "left" }
          - { label: "Right", value: "right" }
          - { label: "Bottom", value: "bottom" }

  - name: "featured"
    label: "Homepage - Featured Events and Activities"
    folder: "content/featured"
    create: false
    delete: false
    slug: "featured"
    identifier_field: "label"
    fields:
      - { label: "Label", name: "label", widget: "string", hint: "This does not appear on the website, but is used to identify this item in the CMS." }
      - label: "Featured Events"
        name: "featured_events"
        widget: "relation"
        collection: "events"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - label: "Featured Activities"
        name: "featured_activities"
        widget: "relation"
        collection: "activities"
        search_fields: ["title"]
        value_field: "title"
        multiple: true

  # FAQ
  - name: "faq"
    label: "FAQ - Items"
    folder: "content/faq"
    create: true
    slug: "{{fields.question}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "markdown", required: true }

  # LIBRARY BOARD
  - name: "board"
    label: "Library Board - Members"
    folder: "content/board"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }

  - name: "policies"
    label: "Library Board - Policies"
    folder: "content/policies"
    create: true
    slug: "{{fields.name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "PDF File", name: "pdf", widget: "file" }
      
  - name: "meetingAgendas"
    label: "Library Board - Meeting Agendas"
    folder: "content/meeting-agendas"
    create: true
    identifier_field: "date"
    slug: "{{date}}"
    preview_path: "{{date}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { label: "PDF File", name: "fileLink", widget: "file" }
      
  - name: "meetingMinutes"
    label: "Library Board - Meeting Minutes"
    folder: "content/meeting-minutes"
    create: true
    identifier_field: "date"
    slug: "{{date}}"
    preview_path: "{{date}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { label: "PDF File", name: "fileLink", widget: "file" }


  # SERVICES
  - name: "services"
    label: "Services - Services"
    folder: "content/services"
    create: true
    identifier_field: "title"
    slug: "{{title}}"
    preview_path: "{{title}}"
    fields:
      - { label: "Icon Class", name: "icon", widget: "string", hint: "Use a Font Awesome icon class (e.g., 'fa-solid fa-comments')" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Button Link", name: "link", widget: "string", required: false }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false }

  # ACTIVITIES
  - name: "activities"
    label: "Activities Page - Activities"
    folder: "content/activities"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order On Activities Page", name: "order", widget: "number", required: true }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false }

  # EVENTS
  - name: "events"
    label: "Event Page - Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false }

  # Resources
  - name: "resources"
    label: "Resources Page - Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string"}
      - { label: "Image", name: "image", widget: "image" }

  # GLOBAL
  - name: "bannerAlert"
    label: "Global - Banner Alert"
    label_singular: "Banner Alert"
    folder: "content/bannerAlert"
    create: false
    delete: false
    slug: "index"
    identifier_field: "text"
    editor:
      preview: false
    fields:
      - { label: "Text", name: "text", widget: "markdown", required: true, hint: "Supports rich text formatting, including bolding, new lines, and hyperlinks." }
      - { label: "Start Date", name: "startDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, required: false, hint: "Optional. If set, the alert will only show after this date. Otherwise, it will show immediately." }
      - { label: "End Date", name: "endDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, required: false, hint: "Optional. If set, the alert will only show until this date. Otherwise, it will show indefinitely until updated." }
      - label: "Color"
        name: "color"
        widget: "select"
        options:
          - { label: "Info (Blue)", value: "info" }
          - { label: "Success (Green)", value: "success" }
          - { label: "Warning (Yellow)", value: "warning" }
          - { label: "Error (Red)", value: "error" }
          - { label: "Default (Gray)", value: "default" }

  - name: "contact"
    label: "Global - Contact Information"
    files:
      - file: "content/contact/contact.md"
        label: "Contact Information"
        name: "contact"
        fields:
          - { label: "Street Address", name: "streetAddress", widget: "string" }
          - { label: "City & Province", name: "cityProvince", widget: "string" }
          - { label: "Postal Code", name: "postalCode", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Facebook Link", name: "facebook", widget: "string" }
          - { label: "Instagram Link", name: "instagram", widget: "string" }
          - { label: "TikTok Link", name: "tiktok", widget: "string" }
          - { label: "Pinterest Link", name: "pinterest", widget: "string" }
  
  - name: "traffic"
    label: "Traffic Counter"
    folder: "src/traffic"
    create: true
    identifier_field: "count"
    fields:
      - { label: "Count", name: "count", widget: "number" }
